site_name: "InstaRoad: Deep Learning Road Network Extraction from Satellite Imagery"
theme: readthedocs

nav:
  - Introduction: index.md
  - Setup Guide: setup.md
  - SAM Road: samroad.md
  - Sentinel2: sentinel2.md
  - Change Log: changelog.md