#!/bin/bash
# SEED REFIT — sr_r2grid_off_ls1e-6_nohc_gap_ce_anorm_recalpost_rails
#
# GENERATED by scripts/local/make_grid_refit_scripts.py. Regenerate rather than
# hand-editing: the overlay below is a verbatim copy of a tune's output.
#
# Replicate seeds of ONE cell of the lr_sr x hard-constraint mechanism grid
# (docs/lrsr_grid_ablation_plan.md): HC=off, lr_sr=1e-06 PINNED — that is the
# cell's coordinate, not something the search chose.
#
#   cd scripts/hpc
#   sbatch --job-name=refit-r2grid_off_ls1e-6 --time=24:00:00 \
#          --gres=gpu:1 --cpus-per-task=8 \
#          train.sbatch --SCRIPT=sr/refit/r2grid_off_ls1e-6.sh
#
# CHANGE THE SEEDS AND NOTHING ELSE:
#   SEEDS="3 4" sbatch ... train.sbatch --SCRIPT=sr/refit/r2grid_off_ls1e-6.sh
# Several cells in one allocation: sr/refit/r2grid_pool.sh.
#
# WHEN TO RUN THIS AT ALL
# -----------------------
# §2 and §10: seed 0 for every cell first, additional seeds ONLY for a cell
# that ends up carrying a QUANTITATIVE sentence. The grid's primary evidence is
# trajectories, band signatures and envelope crossings, and it already
# replicates along the lr_sr axis — four runs per lane, one per decade, with a
# dose-response between them. Seeds buy the error bar on a number, which at n=1
# §4 forbids leaning on anyway; they are not what makes the mechanism claim.
#
# Hyperparameters are seed 0's tune (best val_ap=0.5848  trial #4  alpha=lr_sr/lr=5.36e-03), copied verbatim from
#   /sessions/charming-magical-fermi/mnt/SRruns/sr_r2grid_off_ls1e-6_nohc_gap_ce_anorm_recalpost_rails_seed0
# and baked in, so the cluster needs nothing from SRruns/ and the exact config
# a refit used is readable in the file that ran it. Note the overlay carries
# std_band_raise_lo/hi as well: the refit runs the band the search ran.
#
# THE CELL DEFINITION IS SOURCED, NOT COPIED. _grid_cell.sh sets the lane
# (sr_hc/sr_pad), the band policy (loosened rails, std_band_action=warn), the
# frozen loss control, the protocol (train+val, val_ap, theta* on micro IoU,
# AP_BINS) and the derived RUN_TAG/MODEL_NAME — the same file r2grid_new.sh ran
# for seed 0. RUN_TAG must reproduce _stages_tv.sh's RUN_DIR exactly or the
# seed lands in a directory that does not group with seed 0: a silent no-op
# rather than an error, which is why it is asserted below.
set -euo pipefail
REPO_DIR="${REPO_DIR:-$HOME/InstaRoad/InstaRoadPrototype}"
source "$REPO_DIR/scripts/hpc/sr/refit/_refit_lib.sh"

export HC="off"
export LRSR="1e-06"

# Replicate seeds exist for the NUMBER; the snapshot strips come from seed 0.
# Set SR_SNAPSHOT_EVERY=1 if this seed is meant to replicate the SIGNATURE
# instead (~200 MB of SEN2SR-Lite snapshots per seed at every epoch).
export SR_SNAPSHOT_EVERY="${SR_SNAPSHOT_EVERY:-0}"

source "$REPO_DIR/scripts/hpc/sr/_grid_cell.sh"

# Baked at generation time from the seed-0 run dir; derived at run time by
# _grid_cell.sh. If these ever disagree, the cell definition moved after this
# script was generated — regenerate rather than letting the seed land somewhere
# the store will not group with seed 0.
EXPECTED_RUN_TAG="sr_r2grid_off_ls1e-6_nohc_gap_ce_anorm_recalpost_rails"
if [ "$RUN_TAG" != "$EXPECTED_RUN_TAG" ]; then
  echo "ERROR: _grid_cell.sh derives RUN_TAG='${RUN_TAG}' but this script was" >&2
  echo "  generated for '${EXPECTED_RUN_TAG}'. The cell definition changed." >&2
  echo "  Regenerate: python scripts/local/make_grid_refit_scripts.py" >&2
  exit 2
fi

SEEDS="${SEEDS:-1 2}"

read -r -d '' BEST_PARAMS <<'YAML' || true
model:
  encoder_name: resnet34
  encoder_weights: imagenet
  upsampler: sen2sr
  freeze_sr: false
  sr_pad: 0
  lr: 0.00018662266976517952
  sr_hc: 'off'
  loss_arm: gap_ce
  pstar: gap_ce
  gap_r: 4
  gap_k: 60.0
  tl_ell: 5
  tl_theta: 0.375
  gap_theta: 0.55836
  tversky_alpha: 0.7
  cl_alpha: 0.3
  cl_iters: 5
  sr_w: 1.0
  sr_radius: 1
  warmup_start: 30
  warmup_ramp: 10
  mix_w: 0.6075946831862098
  pos_weight: 4.77222
  lr_sr: 1.0e-06
  lr_schedule: cosine
  sr_warmup_epochs: 1.0
  l2sp_lambda: 0.0
  adaptive_norm: true
  adaptive_norm_momentum: 0.01
  norm_recalibrate: post
  std_band_raise_lo: 0.01
  std_band_raise_hi: 100.0
data:
  batch_size: 4
  mask_source: raster
  mask_dirname: mask_new_2pt5
trainer:
  precision: bf16-mixed
YAML

run_seeds
