#!/bin/bash
# SEED REFIT — sr_r2grid_on_ls1e-6_gap_ce_anorm_recalpost_rails
#
# GENERATED by scripts/local/make_grid_refit_scripts.py. Regenerate rather than
# hand-editing: the overlay below is a verbatim copy of a tune's output.
#
# Replicate seeds of ONE cell of the lr_sr x hard-constraint mechanism grid
# (docs/lrsr_grid_ablation_plan.md): HC=on, lr_sr=1e-06 PINNED — that is the
# cell's coordinate, not something the search chose.
#
#   cd scripts/hpc
#   sbatch --gres=gpu:1 --cpus-per-task=8 --time=24:00:00 \
#          -J r2grid_on_ls1e-6_seeds -o slurm-%x-%j.txt \
#          train.sbatch --SCRIPT=sr/grid/refit/r2grid_on_ls1e-6.sh
#
#   SEEDS="3 4" sbatch ... train.sbatch --SCRIPT=sr/grid/refit/r2grid_on_ls1e-6.sh
#
# A whole lane in one allocation: sr/grid/pool_r2a.sh / pool_r2b.sh with
# STAGES=refit (they drive grid/run_pool.sh, which calls this script per cell).
#
# WHEN TO RUN THIS AT ALL
# -----------------------
# §2 and §10: seed 0 for every cell first, additional seeds ONLY for a cell
# that ends up carrying a QUANTITATIVE sentence. The grid's primary evidence is
# trajectories, band signatures and envelope crossings, and it already
# replicates along the lr_sr axis — four runs per lane, one per decade, with a
# dose-response between them. Seeds buy the error bar on a number, which at n=1
# §4 forbids leaning on anyway; they are not what makes the mechanism claim.
#
# WHY A SCRIPT PER CELL, AND WHY THE OVERLAY IS BAKED
# ---------------------------------------------------
# STAGE=fit refuses to start without ${RUN_DIR}/best_params.yaml, and RUN_DIR
# carries the SEED — a seed-1 dir has never been tuned and never will be. So the
# overlay is PLANTED. Baking it here (rather than copying from seed 0 at run
# time) means the cluster needs nothing from SRruns/, and the exact
# hyperparameters a refit used are readable in the file that ran it. Re-tuning
# per seed would be worse than either: each seed would get its own lr, which is
# a different arm, not a replicate.
#
# Hyperparameters are seed 0's tune (best val_ap=0.5862  trial #6  alpha=lr_sr/lr=4.87e-03), copied verbatim from
#   /Volumes/MAC_KIOXIA/Data/InstaRoad/SRruns/sr_r2grid_on_ls1e-6_gap_ce_anorm_recalpost_rails_seed0
# Note the overlay carries std_band_raise_lo/hi too, so the refit runs the band
# the search ran.
#
# THE CELL ITSELF IS NOT RE-DESCRIBED HERE. Every stage runs through
# r2grid_new.sh with this cell's HC/LRSR, so the lane, the band policy
# (loosened rails + std_band_action=warn), the frozen loss control and the
# protocol are whatever that script says they are — one definition of a cell,
# the one that produced seed 0. The names come from the engine too
# (PRINT_RUN_DIR): RUN_DIR must match seed 0's exactly, or these seeds land in
# a directory the store will not group with it — a silent no-op, not an error.
set -euo pipefail
REPO_DIR="${REPO_DIR:-$HOME/InstaRoad/InstaRoadPrototype}"
USER_NAME="${USER:-$(whoami)}"
# ckpt_epoch / fit_state / in_store — the same resume guards the seed-0 pool
# uses, so a finished seed costs seconds and a partial one resumes.
source "$REPO_DIR/scripts/hpc/sr/refit/_refit_lib.sh"

CELL_SCRIPT="$REPO_DIR/scripts/hpc/sr/r2grid_new.sh"
export HC="on"
export LRSR="1e-06"
EXPECTED_RUN_TAG="sr_r2grid_on_ls1e-6_gap_ce_anorm_recalpost_rails"

SEEDS="${SEEDS:-1 2}"
STORE_DIR="${STORE_DIR:-/scratch/${USER_NAME}/InstaRoad/benchmarks_corrected}"
REFIT_EPOCHS="${REFIT_EPOCHS:-100}"

# Replicate seeds exist for the NUMBER; the snapshot strips come from seed 0.
# Set SR_SNAPSHOT_EVERY=1 if this seed is meant to replicate the SIGNATURE
# instead (~200 MB of SEN2SR-Lite snapshots per seed at every epoch).
export SR_SNAPSHOT_EVERY="${SR_SNAPSHOT_EVERY:-0}"
# Grid cells are EXPECTED to collapse or die numerically (§3), and a dead cell
# you cannot resume or re-inspect is one you re-run from zero. Same reason
# grid/run_pool.sh keeps it; the opposite of the formal arms' default.
KEEP_LAST="${KEEP_LAST:-1}"

read -r -d '' BEST_PARAMS <<'YAML' || true
model:
  encoder_name: resnet34
  encoder_weights: imagenet
  upsampler: sen2sr
  freeze_sr: false
  sr_pad: 8
  lr: 0.00020547625125911338
  loss_arm: gap_ce
  pstar: gap_ce
  gap_r: 4
  gap_k: 60.0
  tl_ell: 5
  tl_theta: 0.375
  gap_theta: 0.55836
  tversky_alpha: 0.7
  cl_alpha: 0.3
  cl_iters: 5
  sr_w: 1.0
  sr_radius: 1
  warmup_start: 30
  warmup_ramp: 10
  mix_w: 0.6075946831862098
  pos_weight: 4.77222
  lr_sr: 1.0e-06
  lr_schedule: cosine
  sr_warmup_epochs: 1.0
  l2sp_lambda: 0.0
  adaptive_norm: true
  adaptive_norm_momentum: 0.01
  norm_recalibrate: post
  std_band_raise_lo: 0.01
  std_band_raise_hi: 100.0
data:
  batch_size: 4
  mask_source: raster
  mask_dirname: mask_new_2pt5
trainer:
  precision: bf16-mixed
YAML

run_cell () {   # stage seed [KEY=VALUE ...]
  local stage="$1" seed="$2"; shift 2
  env HC="$HC" LRSR="$LRSR" SEED="$seed" STAGE="$stage" \
      STORE_DIR="$STORE_DIR" REFIT_EPOCHS="$REFIT_EPOCHS" \
      ${NUM_WORKERS:+NUM_WORKERS="$NUM_WORKERS"} "$@" \
      bash "$CELL_SCRIPT"
}

for SEED in $SEEDS; do
  if [ "$SEED" = "0" ]; then
    echo "########## ${EXPECTED_RUN_TAG}  SEED=0 skipped: that is the TUNED seed," >&2
    echo "##########   whose overlay this script was generated FROM. Re-run it" >&2
    echo "##########   through r2grid_new.sh if you really mean to redo it." >&2
    continue
  fi

  # Names from the engine, never rebuilt: it composes them from a tag chain
  # that grows (ES_TAG arrived after this grid first ran), and one stale tag
  # makes every guard inspect a directory the run will never write.
  NAMES=$(env HC="$HC" LRSR="$LRSR" SEED="$SEED" PRINT_RUN_DIR=1 \
              bash "$CELL_SCRIPT" 2>/dev/null)
  RUN_DIR=$(printf '%s\n' "$NAMES" | sed -n 's/^RUN_DIR=//p')
  MODEL_NAME=$(printf '%s\n' "$NAMES" | sed -n 's/^MODEL_NAME=//p')
  if [ -z "$RUN_DIR" ] || [ -z "$MODEL_NAME" ]; then
    echo "ERROR: could not resolve this cell's names from the engine." >&2
    exit 2
  fi
  RUN_TAG="${RUN_DIR##*/}"
  RUN_TAG="${RUN_TAG%_seed${SEED}}"
  if [ "$RUN_TAG" != "$EXPECTED_RUN_TAG" ]; then
    echo "ERROR: the engine names this cell '${RUN_TAG}' but this script was" >&2
    echo "  generated against '${EXPECTED_RUN_TAG}' — the dir the baked overlay" >&2
    echo "  came from. Seeds planted now would not join seed 0's rows." >&2
    echo "  Regenerate: python scripts/local/make_grid_refit_scripts.py" >&2
    exit 2
  fi

  mkdir -p "$RUN_DIR"
  printf '%s\n' "$BEST_PARAMS" > "$RUN_DIR/best_params.yaml"

  state=fresh
  [ "${FORCE_FIT:-0}" = "1" ] || state=$(fit_state "$RUN_DIR" "$REFIT_EPOCHS")
  resume=0
  case "$state" in
    done)
      echo "########## ${RUN_TAG}  SEED=${SEED}  FIT complete (>=${REFIT_EPOCHS} epochs + sweep.json) — skipping ##########" ;;
    sweep_only)
      echo "########## ${RUN_TAG}  SEED=${SEED}  weights complete but no sweep.json ##########"
      echo "##########   resuming to reach the theta* sweep — no epoch is retrained ##########"
      resume=1 ;;
    resume)
      echo "########## ${RUN_TAG}  SEED=${SEED}  partial fit — RESUMING from last.ckpt ##########"
      echo "##########   (FORCE_FIT=1 to discard it and train from scratch) ##########"
      resume=1 ;;
    sweep_only_nolast)
      echo "########## ${RUN_TAG}  SEED=${SEED}  weights complete, sweep.json missing," >&2
      echo "##########   last.ckpt gone: the fit cannot be resumed and retraining" >&2
      echo "##########   ${REFIT_EPOCHS} epochs is refused. Produce sweep.json by hand" >&2
      echo "##########   (see _refit_lib.sh) or set FORCE_FIT=1. ##########" >&2
      continue ;;
    fresh)
      echo "########## ${RUN_TAG}  SEED=${SEED}  FIT (${REFIT_EPOCHS} epochs, train+val) ##########" ;;
  esac
  if [ "$state" != "done" ]; then
    if ! run_cell fit "$SEED" RESUME_FIT="$resume"; then
      # A cell that dies numerically is a RESULT (§3), not a script failure:
      # record where it got to and carry on to the next seed.
      echo "########## ${RUN_TAG}  SEED=${SEED}  FIT FAILED — see the log for the step" >&2
      echo "##########   it reached; numerical death at step X is an observation. ##########" >&2
      continue
    fi
  fi

  # test only — val was folded into training, so there is no honest val row.
  if in_store "$STORE_DIR" "$MODEL_NAME" "$SEED" test; then
    echo "########## ${RUN_TAG}  SEED=${SEED}  BENCH test already in the store — skipping ##########"
    echo "##########   (append-only, no dedupe: a second row double-counts this seed) ##########"
  elif [ ! -f "${RUN_DIR}/sweep.json" ]; then
    echo "########## ${RUN_TAG}  SEED=${SEED}  no sweep.json — bench has no theta*, skipping ##########" >&2
  else
    echo "########## ${RUN_TAG}  SEED=${SEED}  BENCH test (at the refit's theta*) ##########"
    run_cell bench "$SEED" MODEL_NAME="$MODEL_NAME" || \
      echo "########## ${RUN_TAG}  SEED=${SEED}  BENCH FAILED — continuing ##########" >&2
  fi

  [ "$KEEP_LAST" = "1" ] || rm -f "${RUN_DIR}/checkpoints/last.ckpt"
done

echo "=== sr_r2grid_on_ls1e-6_gap_ce_anorm_recalpost_rails: seeds ${SEEDS} done ==="
