"""Train the R0/R1/R2 resolution-enhancement experiments (Lightning).

Reads the V2 tiled dataset layout (`sentinel2data generate`) directly:
    <data>/splits/{train,val,test}.csv          split CSVs (tile-level rows)
    <data>/<split>/imagery/{tile}.tif           23-band 10 m tile COGs (only
                                                the [B4, B3, B2, B8] slice,
                                                bands 1-4, is used)
    <data>/<split>/masks_osm_2pt5m/{tile}.tif   OSM road masks on the 2.5 m
                                                grid (exactly 4x tile dims),
                                                pre-generated by
                                                OpenStreetMapTest/dataset_hr_masks.py
    <norm-stats yaml or npz>                    frozen per-band mean/std
                                                (adapter stats; from
                                                `sentinel2data norm-stats`)

The split comes from the shared split CSVs, so it matches the baseline and
benchmarking exactly. Logs to Weights & Biases, early-stops on val loss,
checkpoints the best model to `--out`.

Experiments (one module, only the upsampler treatment varies):
    R0  bicubic x4 input upsampling (deterministic baseline)
    R1  SEN2SR frozen preprocessing
    R2  SEN2SR fine-tuned jointly via the segmentation loss alone
        (task-driven SR; differential LRs implement the Figure-1 alpha)

Run:
    python -m sr.train --data /scratch/.../InstaRoad --experiment R2 --out runs/sr_r2
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import lightning as L
import numpy as np
from lightning.pytorch.callbacks import EarlyStopping, ModelCheckpoint
from lightning.pytorch.loggers import WandbLogger
from torch.utils.data import DataLoader

from sr.data import (
    HR_MASKS_DIRNAME,
    SR_BANDS,
    SRRoadSegDataset,
    compute_pos_weight,
    loader_kwargs,
)
from sr.module import LOSS_REGISTRY, JointSRSegModule
from sr.sen2sr_loader import download_sen2sr

# experiment id -> (upsampler, freeze_sr)
EXPERIMENTS = {
    "R0": ("bicubic", False),
    "R1": ("sen2sr", True),
    "R2": ("sen2sr", False),
}


def load_band_stats(path: Path) -> tuple[tuple, tuple]:
    """Frozen per-band mean/std (DN units), sliced to the [B4,B3,B2,B8] adapter
    bands. Accepts the pipeline's norm_stats.yaml (`data.norm_mean/norm_std`,
    full 23-band 1-based stack from `sentinel2data norm-stats`) or a legacy
    Data.npz with `mean`/`std` arrays."""
    if not path.exists():
        raise SystemExit(
            f"Band stats not found at {path}. Generate with:\n"
            f"  python -m sentinel2data.cli norm-stats --dataset-dir <root> --out {path}"
        )
    idx = [b - 1 for b in SR_BANDS]
    if path.suffix == ".npz":
        st = np.load(path)
        mean, std = st["mean"], st["std"]
    else:
        import yaml
        cfg = yaml.safe_load(path.read_text())
        d = cfg.get("data", cfg)
        mean, std = d["norm_mean"], d["norm_std"]
    return (tuple(float(mean[i]) for i in idx),
            tuple(float(std[i]) for i in idx))


def parse_args():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data", required=True,
                    help="V2 dataset root (contains splits/, <split>/imagery/)")
    ap.add_argument("--hr-masks-dirname", default=HR_MASKS_DIRNAME,
                    help="OSM HR-mask dir name beside each split's imagery/ "
                         f"(default {HR_MASKS_DIRNAME}; see dataset_hr_masks.py)")
    ap.add_argument("--stats", default=None,
                    help="frozen per-band stats: norm_stats.yaml from "
                         "`sentinel2data norm-stats` or a legacy Data.npz "
                         "(default <data>/norm_stats.yaml)")
    ap.add_argument("--min-road-density", type=float, default=0.0,
                    help="drop TRAIN tiles below this road fraction "
                         "(val stays unfiltered); mirrors unet_upscale's filter")
    ap.add_argument("--out", required=True, help="output dir for checkpoints + metadata")
    ap.add_argument("--experiment", default="R2", choices=list(EXPERIMENTS))
    ap.add_argument("--sen2sr-dir", default=None,
                    help="mlstac SEN2SR model dir (default <data>/models/SEN2SRLite_RGBN)")
    ap.add_argument("--download-sen2sr", action="store_true",
                    help="fetch SEN2SR weights if missing (needs internet — run on a login node)")
    ap.add_argument("--epochs", type=int, default=50)
    ap.add_argument("--batch-size", type=int, default=4,
                    help="512x512 U-Net stage is memory-heavy; 4 fits comfortably in 48GB at bf16")
    ap.add_argument("--lr-seg", type=float, default=1e-3, help="U-Net LR (baseline's default)")
    ap.add_argument("--lr-sr", type=float, default=1e-5,
                    help="SEN2SR LR; alpha = lr_sr/lr_seg. Keep well below lr-seg")
    ap.add_argument("--freeze-sr-steps", type=int, default=0,
                    help="hold the SR LR at 0 for this many steps (warm-up)")
    ap.add_argument("--sr-lr-ramp-steps", type=int, default=0,
                    help="after the hold, ramp the SR LR linearly to lr-sr over this many steps")
    ap.add_argument("--scheduler", default="none", choices=["none", "cosine"])
    ap.add_argument("--loss", default="roadseg", choices=list(LOSS_REGISTRY))
    ap.add_argument("--alpha", type=float, default=0.3, help="clDice weight in RoadSegLoss")
    ap.add_argument("--patch-size", type=int, default=128,
                    help="10m patch; SEN2SR's shipped FFT mask pins this to 128")
    ap.add_argument("--stride", type=int, default=128)
    ap.add_argument("--encoder", default="resnet34",
                    help="smp encoder for the baseline U-Net; keep constant across R0/R1/R2")
    ap.add_argument("--aug-flip", action=argparse.BooleanOptionalAction, default=True,
                    help="D4 flips + rotations on the train split (default: on)")
    ap.add_argument("--num-workers", type=int, default=4)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--patience", type=int, default=10)
    ap.add_argument("--min-delta", type=float, default=1e-4)
    ap.add_argument("--precision", default="bf16-mixed",
                    help="Lightning precision (bf16-mixed recommended; 32-true for CPU debugging)")
    ap.add_argument("--accelerator", default="auto",
                    help="Lightning accelerator; pass 'cpu' to keep laptop debug runs light")
    ap.add_argument("--devices", type=int, default=1)
    ap.add_argument("--deterministic", action="store_true",
                    help="torch deterministic algorithms (warn-only; some SR ops lack kernels)")
    ap.add_argument("--log-grad-norms-every", type=int, default=100,
                    help="log per-group grad norms every N steps (0 = off)")
    ap.add_argument("--wandb-project", default="instaroad-baseline")
    ap.add_argument("--wandb-mode", default="online", choices=["online", "offline", "disabled"])
    ap.add_argument("--model-name", default=None, help="run/model name (default: sr_<experiment>)")
    return ap.parse_args()


def main():
    args = parse_args()
    L.seed_everything(args.seed, workers=True)

    data = Path(args.data)
    stats = Path(args.stats) if args.stats else data / "norm_stats.yaml"
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    model_name = args.model_name or f"sr_{args.experiment.lower()}"
    upsampler, freeze_sr = EXPERIMENTS[args.experiment]

    sen2sr_dir = Path(args.sen2sr_dir) if args.sen2sr_dir else data / "models" / "SEN2SRLite_RGBN"
    if upsampler == "sen2sr" and not (sen2sr_dir / "model.safetensor").exists():
        if args.download_sen2sr:
            download_sen2sr(sen2sr_dir)
        else:
            raise SystemExit(
                f"SEN2SR weights not found at {sen2sr_dir}. Run once with "
                f"--download-sen2sr on a node with internet, or pass --sen2sr-dir."
            )

    print(f"experiment={args.experiment} ({upsampler}, freeze_sr={freeze_sr})  "
          f"hr_masks={args.hr_masks_dirname!r}")

    train_ds = SRRoadSegDataset(data, "train", hr_masks_dirname=args.hr_masks_dirname,
                                patch_size=args.patch_size, stride=args.stride,
                                d4=args.aug_flip,
                                min_road_density=args.min_road_density)
    val_ds = SRRoadSegDataset(data, "val", hr_masks_dirname=args.hr_masks_dirname,
                              patch_size=args.patch_size, stride=args.patch_size)
    print(f"patches  train={len(train_ds)}  val={len(val_ds)}  "
          f"augment={'flip' if args.aug_flip else 'off'}")

    kwargs = loader_kwargs(args.num_workers)
    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                              drop_last=True, **kwargs)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False, **kwargs)

    # pos_weight from the actual 2.5m road frequency over the train masks.
    pos_weight = compute_pos_weight(data, "train", args.hr_masks_dirname)
    print(f"pos_weight={pos_weight.item():.2f}")

    band_mean, band_std = load_band_stats(stats)

    module = JointSRSegModule(
        upsampler=upsampler, sen2sr_dir=str(sen2sr_dir) if upsampler == "sen2sr" else None,
        band_mean=band_mean, band_std=band_std,
        encoder=args.encoder, loss=args.loss,
        pos_weight=pos_weight.item(), alpha=args.alpha,
        lr_sr=args.lr_sr, lr_seg=args.lr_seg,
        freeze_sr=freeze_sr, freeze_sr_steps=args.freeze_sr_steps,
        sr_lr_ramp_steps=args.sr_lr_ramp_steps, scheduler=args.scheduler,
        log_grad_norms_every=args.log_grad_norms_every,
    )

    logger = WandbLogger(project=args.wandb_project, name=model_name,
                         mode=args.wandb_mode, save_dir=str(out))
    logger.log_hyperparams(vars(args))
    ckpt_cb = ModelCheckpoint(dirpath=out, filename="best", monitor="val_loss",
                              mode="min", save_top_k=1, save_last=True)
    early_cb = EarlyStopping(monitor="val_loss", mode="min",
                             patience=args.patience, min_delta=args.min_delta)

    trainer = L.Trainer(
        max_epochs=args.epochs,
        accelerator=args.accelerator, devices=args.devices,
        precision=args.precision,
        logger=logger,
        callbacks=[ckpt_cb, early_cb],
        deterministic="warn" if args.deterministic else False,
        default_root_dir=str(out),
        log_every_n_steps=10,
    )
    trainer.fit(module, train_loader, val_loader)

    best_val = ckpt_cb.best_model_score
    # Record where training landed so the eval stage can pick it up unambiguously.
    (out / "train_meta.json").write_text(json.dumps({
        "model_name": model_name,
        "experiment": args.experiment,
        "upsampler": upsampler,
        "freeze_sr": freeze_sr,
        "encoder": args.encoder,
        "seed": args.seed,
        "lr_sr": args.lr_sr,
        "lr_seg": args.lr_seg,
        "best_val_loss": float(best_val) if best_val is not None else None,
        "checkpoint": ckpt_cb.best_model_path,
        "data": str(data),
        "hr_masks_dirname": args.hr_masks_dirname,
        "min_road_density": args.min_road_density,
        "stats": str(stats),
        "sen2sr_dir": str(sen2sr_dir) if upsampler == "sen2sr" else None,
        "patch_size": args.patch_size,
    }, indent=2))
    print(f"done. best val loss "
          f"{float(best_val) if best_val is not None else float('nan'):.4f} "
          f"at {ckpt_cb.best_model_path}")


if __name__ == "__main__":
    main()
