seed_everything: 42

trainer:
  max_epochs: 1
  accelerator: auto
  devices: auto
  log_every_n_steps: 50
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: dlinknet_sentinel2_baseline
      config:
        learning_rate: 0.001
        architecture: DLinkNet34
        encoder: resnet34
        dataset: Sentinel-2
        epochs: 1
        batch_size: 4
        image_size: 1024
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: /kaggle/working/checkpoints
        filename: dlinknet34_resnet34
        monitor: val_loss
        mode: min
        save_top_k: 1
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

model:
  class_path: src.utils.lightning_utils.LightningWrapper
  init_args:
    learning_rate: 0.001
    threshold: 0.5
    model:
      class_path: dlinknet.networks.dinknet.DinkNet34
      init_args:
        num_classes: 1
        num_channels: 3

data:
  class_path: src.utils.lightning_dataset.SentinelDataModule
  init_args:
    base_dir: /kaggle/working/InstaRoadPrototype/dataset/S2IndianRegions
    dataset_dir: /kaggle/working/InstaRoadPrototype/dataset/sentinel2/sentinel2_256/15765738
    image_size: 1024
    train_batch_size: 4
    eval_batch_size: 16
    num_workers: 2
    transform:
      class_path: albumentations.Compose
      init_args:
        transforms:
          - class_path: albumentations.Resize
            init_args:
              height: 1024
              width: 1024
          - class_path: albumentations.Normalize
            init_args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]